# -*- coding: utf-8 -*-
"""IGTI-Bootcamp-Cientista-De-Dados-Modulo-1-Trabalho-Pratico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qjw2Gt2W3BfEZCSfKKHL792rEbEkzngs
"""

# Importando a bibliotecas
from math import sqrt
from matplotlib import pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

# Criando o dataset - questão 3
X, y = make_blobs(n_samples=500, centers=20, random_state=999)
plt.scatter(X[:,0], X[:,1])

# A partir do WCSS determinar o número de clusters
wcss = []
for i in range(1, 20):
    kmeans = KMeans(n_clusters=i, init='k-means++', max_iter=300, n_init=10)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)
n = optimal_number_of_clusters(wcss)
print(f'Numero de clusters: ', n)

# questão 4
kmeans = KMeans(n_clusters=1, init='random') # seta o número de cluster para 1, conforme a pergunta 4
kmeans.fit(X) 

kmeans.cluster_centers_ # mostra o resultado da pergunta 4 (array([[ 0.02618523, -1.30384304]]))

# questões 5 e 6

wcss = []	
for i in range(1, 20):
    kmeans = KMeans(n_clusters=i, init='k-means++', max_iter=300, n_init=10)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)
    print('Clusters:', i, ' / wcss =', wcss[i-1]) # o output do primeiro cluster mostra o resultado da pergunta 5 (Clusters: 1  / wcss = 31547.372471390485) e o output do quinto cluster mostra o resultado da pergunta 6 (Clusters: 5  / wcss = 4717.404091931214)

plt.plot(range(1, 20), wcss)
plt.plot([1, 19],[wcss[0], wcss[len(wcss)-1]])
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.grid()
plt.show()

# questão 7


wcss = []
for i in range(1, 20):
    kmeans = KMeans(n_clusters=i, init='k-means++', max_iter=300, n_init=10)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)
n = optimal_number_of_clusters(wcss)
print(n)